In [1]:
import numpy as np

In [12]:
a= np.arange(15)
a= np.arange(15).reshape(15,1)
print(a)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]


In [5]:
a.size

15

In [6]:
a.ndim

2

In [7]:
a.dtype

dtype('int32')

In [13]:
a.shape

(15, 1)

In [25]:
c=np.array([[1,2],[3,4]],dtype= complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [24]:
z =np.array([(1.2,2,3),(4,5,6)])
print(z)


[[1.2 2.  3. ]
 [4.  5.  6. ]]


In [23]:
zeros= np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
ones =np.ones((2,3,4),dtype=np.int16)
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [21]:
cd = np.arange(0,2,0.3)
print(cd)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [20]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
a = np.array([20,30,40,50])
b= np.arange(4)
c= a-b

In [28]:
b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

In [29]:
A =np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
prod1 = A*B
prod2 = A@B
prod3=A.dot(B)

In [30]:
a =np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
b+=a

In [33]:
a =np.random.random((2,3))
a.sum()
a.min()
a.max()

0.8984308486776549

In [34]:
b[0:5,1]


array([3.87858362, 3.26522588])

In [35]:
b[:,1]

array([3.87858362, 3.26522588])

In [37]:
b[1:3,:]

array([[3.23617928, 3.26522588, 3.43475647]])

In [39]:
a= np.floor(10*np.random.random((2,2)))
b= np.floor(10*np.random.random((2,2)))



In [40]:
np.vstack((a,b))

array([[7., 8.],
       [0., 6.],
       [4., 2.],
       [5., 4.]])

In [41]:
np.hstack((a,b))

array([[7., 8., 4., 2.],
       [0., 6., 5., 4.]])

In [42]:
a= np.floor(10*np.random.random((2,12)))
np.hsplit(a,3)#split into 3
np.hsplit(a,(3,4)) #spli after 3rd and 4rth colnm

[array([[3., 4., 8.],
        [0., 3., 1.]]),
 array([[4.],
        [3.]]),
 array([[4., 6., 4., 7., 0., 7., 3., 7.],
        [6., 9., 7., 3., 8., 6., 3., 0.]])]